### ISSUE TITLE
Compression format 2 (Oodle?)

### ISSUE THREAD

**Issue by computerquip** [zhyupe/FFXIV-Packet-Dissector#10]
Patch 6.3 (I think?) introduced a new compression format for packets. As far as I can tell, this is done via proprietary Oodle libraries. Unfortunately, I don't know much about these formats. Currently the dissector will error out in that case.

Just for some history on this, it used to be the compression byte meant either no compression or headerless inflated data. It used to be that doing a check for `if compression == 1: deflate` was fine but now it's not. If the compression byte is 2, the new format is used which again, as far as I can tell, is some format from Oodle.

**Comment by zhyupe** [comment]
Afaik it's impossible to implement Oodle decompression in this lua dissector, especially as the current game version using Oodle TCP which requires a "state". This is why this project hasn't been updated since Oodle is deployed.
A better solution would be implementing a wrapper of [Machina](https://github.com/ravahn/machina) or [Deucalion](https://github.com/ff14wed/deucalion) which exports raw packets and save them as `.pcapng`. (I do have a old script for this job before Oodle. Maybe I would update that.)

For now, you should use [ffxivmon](https://github.com/SapphireServer/ffxivmon) for packet analyzing.

**Comment by zhyupe** [comment]
Fixed by #11
