### ISSUE TITLE
how to get the opcode used in chinese server

### ISSUE THREAD

**Issue by FairyScript** [zhyupe/FFXIV-Packet-Dissector#4]
I noticed that some opcode have not be handled.Where should I get data to supplement them?

**Comment by zhyupe** [comment]
Not all packets are being analyzed, either by this project or the others.
But Sapphire has a rather large amount of opcodes and packet structures
where I had copied some from.

BTW not all packet structures provided by Sapphire are correct. For
example, CFNotify and CFNotifyPop (content finder events) has changed a lot
in 5.1, and their structs hasn't been updated yet. In addition, as SQUARE
ENIX randomized all the opcodes since CN 5.1, you can no longer simply copy
the codes from corresponding version of the international servers. But they
are still good for reference.

**Comment by FairyScript** [comment]
get it.
may I push some analysis results into this repo? I'll use the Sapphire's name-style

**Comment by zhyupe** [comment]
Of course. There is [a tool](https://github.com/zhyupe/FFXIV-Packet-Dissector/blob/master/tools/cpp2json.js) with which you can convert the structs to JSON schema.
